### PR TITLE
Client GUI Server Ability

### PR DESCRIPTION
**Pull request by Humungus-Fungus**
- Triggering abilities is now clientside (no server calls). This is **only** for the gui/aiming reticle for the ability.
- Casting abilities remains serverside.
- Abilities now appear on the screen of non-server clients as well.
- Fixed minor bugs involving mana being used up even when an ability is on cooldown and incorrect abilities being on cooldown.

### CODE REVIEW

**Comment by Humungus-Fungus** [comment]
This addresses #40

**Comment by cmkrist** [comment]
I'll test this in the morning before merge

**Comment by InAJacket** [comment]
Code looks good to me, but haven't tested.

**Comment by cmkrist** [comment]
Tested, Pulling

**Pull request merged**
