### PR TITLE
Damage popups, warning shutups

### PR DESCRIPTION
**Pull request by konradybcio**

### CODE REVIEW

**Comment by cmkrist** [comment]
DamagePopup and TimeElapsed need lowercase, code looks good but haven't pulled yet

**Comment by noah1510** [comment]
Do you mind recreating the pr for the 4.3_update branch?
Keep in mind that the new code has multiple damage types, so different colors for them will be required.

**Comment by konradybcio** [comment]
yes, eventually.. unless someone has time and is willing to look into this earlier, then go for it

**Comment by noah1510** [comment]
Then I will create an implementation based on this later myself. I'll tag you in the commit to make it clear the original idea was by you.

**Comment by noah1510** [comment]
It's implemented and working in f951406

**Pull request closed without merging**
