### PR TITLE
Retexture of towers

### PR DESCRIPTION
**Pull request by kuroki100**
-Created scenes for the red and blue towers.
-Added folders for the Tower assets to keep it organized. 
-Fixed the Blue core not using the right material.
-Fixed Core folder not having a textures folder.

### CODE REVIEW

**Comment by noah1510** [comment]
You renamed some folders to uppercase. All files and folders have to be lowercase only.

**Comment by kuroki100** [comment]
ops, ill fix it now

**Comment by kuroki100** [comment]
fixed the uppercase issues and cleaned up the folders a bit to make things less confusing for anyone using the models

**Comment by noah1510** [comment]
The materials still contain uppercase letters

**Comment by noah1510** [comment]
I just looked over the actual contents. I think instead of having one tower scene/class per team/color it would be better  to just have one tower class and set the banner and crystal material to the correct value during the setup. This would make it very easy to have team banners and game modes with more than two teams without all the code duplication.

**Pull request merged**
